### PR TITLE
W22 6pm 2 nx personal schedule table admins

### LINKED ISSUE #47: Table component for PersonalSchedules admin
# Description
Front End Crud personal schedules (admin)
You'll need a table to display personal schedules, with buttons for edit and delete; or just reuse the code for the component for regular users; but add an extra column for admins showing the user that "owns" the personal schedule item".

Also reuse the form for editing.

It is not necessary to allow admins to create personal schedules for other users.

It should NOT be permitted to change the owner ship of a personal schedule; the user id should be not editable.

# Acceptance Criteria

- [x] The table has columns for database fields (i.e. the attributes of the corresponding `@Entity` class
- [x] There are fixtures under `/frontend/src/fixtures` for this data type, similar to the other fixtures files.
- [x] Edit button
- [x] Delete button
- [x] Extra column for admins showing the user that "owns" the personal schedule item".
- [x] There is a storybook entry for `AdminPersonalSchedulesTable`
- [x] 100% coverage with `npm run coverage`
- [x] 100% coverage with `npx stryker run`

### PR DESCRIPTION
**Pull request by alexactss**
# Overview

Added PersonalSchedule table component for admins
It shows { id, user, name, description, quarter} for each personalschedule, with edit and delete buttons

# Issues Addressed

Closes #47 

# Details
Storybook
image

### CODE REVIEW

**Review by ZeyuanLu — DISMISSED** [review]
LGTM

**Review by Lai-Justin — DISMISSED** [review]
LGTM

**Comment by andrewhlu** [comment]
This PR appears to be dependent on #40. Holding off on reviewing / merging this one until that one is resolved.

**Comment by alexactss** [comment]
> This PR appears to be dependent on #40. Holding off on reviewing / merging this one until that one is resolved.

I created new files for admin table component and made some changes based on the requirements, so it should be independent.

**Comment by alexactss** [comment]
Fixed the same problem with #40, pointed out by Andrew.
Merged separate util file into table component.

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
