### PR TITLE
W22 6pm 2 nx personal schedule place holders

### LINKED ISSUE #20: Add PersonalSchedules menu and page placeholders for Users
Add PersonalSchedules menu and page placeholders

The menu shows up only when logged in.  It has only one item for regular users (List) and two items for Admin users (List and Create). These links go to placeholder pages PersonalSchedulesIndexPage and PersonalSchedulesCreatePage.

# Navbar related Acceptance Criteria

- [x] There is a menu item PersonalSchedules (this is done in `AppNavbar.js`)
- [x] The menu item on the navbar only shows up when you are logged in.
- [x] It has two items for Admins, List and Create
- [x] It has two items for regular Users, List and Create
- [x] List routes to  `/personalschedules/list`
- [x] Create routes to  `/personalschedules/create`

# Page related acceptance criteria

- [x] There are pages components under `/frontend/src/main/pages/PersonalSchedules/` for `PersonalSchedulesIndexPage.js` and `PersonalSchedulesCreatePage.js`
- [x] There are entries for these pages in the storybook.
- [x] The List placeholder page is available at `/personalschedules/list` (this is done in `App.js`)
- [x] The Create placeholder page is available at `/personalschedules/create` (this is done in `App.js`)

### PR DESCRIPTION
**Pull request by alexactss**
# Overview

Added PersonalSchedules menu and page placeholders

# Issues Addressed

Closes #20 

# Details
menu

List placeholder page

Create placeholder page

Coverage Test
image
Stryker Test
image

### CODE REVIEW

**Comment by alexactss** [comment]
Accidentally pushed backend files. 
Now they are deleted.

**Review by Lai-Justin — APPROVED** [review]
LGTM

**Review by Jarmstrong845 — APPROVED** [review]
LGTM

**Review by ericwu323 — APPROVED** [review]

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
